// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkCD4Y1UZHSyUZxvcMZA0b0pB47r8Yq44',
    appId: '1:602958300866:web:30f512195a37554c611d5b',
    messagingSenderId: '602958300866',
    projectId: 'oculoo02',
    authDomain: 'oculoo02.firebaseapp.com',
    storageBucket: 'oculoo02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAbBcmi6f0yXnEbBniiGjVwCbQYkATSiQ',
    appId: '1:602958300866:android:1b4f264d83b2a5ad611d5b',
    messagingSenderId: '602958300866',
    projectId: 'oculoo02',
    storageBucket: 'oculoo02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeqxD4pxBr29obSsb-ok959u-fZ2RHlzM',
    appId: '1:602958300866:ios:5ceec99e540b6627611d5b',
    messagingSenderId: '602958300866',
    projectId: 'oculoo02',
    storageBucket: 'oculoo02.firebasestorage.app',
    iosBundleId: 'com.example.oculoo02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeqxD4pxBr29obSsb-ok959u-fZ2RHlzM',
    appId: '1:602958300866:ios:5ceec99e540b6627611d5b',
    messagingSenderId: '602958300866',
    projectId: 'oculoo02',
    storageBucket: 'oculoo02.firebasestorage.app',
    iosBundleId: 'com.example.oculoo02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkCD4Y1UZHSyUZxvcMZA0b0pB47r8Yq44',
    appId: '1:602958300866:web:54f63a83cdc3de86611d5b',
    messagingSenderId: '602958300866',
    projectId: 'oculoo02',
    authDomain: 'oculoo02.firebaseapp.com',
    storageBucket: 'oculoo02.firebasestorage.app',
  );
}
